### ISSUE TITLE
TLS 1.2+ support

### ISSUE THREAD

**Issue by dotcypress** [wizfi/Release#1]
**Issue Type** : Wish

**AT version** : 1.1.0.7

**Board Type** : WizFi360 Shield V1.0

**Module Type** : PA

**Condition** : SSL

**Description** : 

The device we developing must support SSL for downloading application data and all our web-servers support TLS 1.2 and TLS 1.3 connections *only*.
I did some blackbox testing and looks like WizFi with the latest firmware(1.1.0.7) failed to establish TLS 1.2+ connection.

**Describe the solution you'd like**
Could you include TLS 1.2+ support with the next release of firmware?

**Comment by dotcypress** [comment]
@taylor-an friendly reminder on this 😃

**Comment by taylor-an** [comment]
Hello,
Did you run AT+CASEND=1 for upload certification?

**Comment by dotcypress** [comment]
@taylor-an Yes, I tried with certificates as well.
I deploy a simple test app here: https://wizfi.vercel.app and you can try it:`AT+CIPSTART="SSL","wizfi.vercel.app",443`

**Comment by dotcypress** [comment]
@taylor-an any updates on this? 😄

**Comment by dotcypress** [comment]
Fixed in AT verison 1.1.1.2.

Thank you guys!
